import './globals.css'
import type { Metadata } from 'next'
import { Newsreader } from 'next/font/google'
import Link from 'next/link'
import bg from '../public/images/zion.jpeg'

const newsreader = Newsreader({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${newsreader.className} flex flex-col items-center content-center`}
      >
        <div className="w-10/12">
          <main className="pt-28">{children}</main>
        </div>
      </body>
    </html>
  )
}
