import './globals.css'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import Link from 'next/link'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/e2a9be5813.js"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body
        className={`${outfit.className} flex flex-col items-center content-center bg-gradient-to-r from-gray-950 from-90% to-blue-950 to-100% text-gray-200`}
      >
        <div className="w-10/12" style={{ maxWidth: '1024px' }}>
          <main className="pt-8">
            <section className="py-6 px-12 grid grid-cols-3 gap-4 max-h-96">
              <h1 className="text-center text-5xl font-bold col-span-2">
                <Link className="text-white" href="/">
                  JS
                </Link>
              </h1>
              <div></div>
              <section className="px-4 pt-4 border-l-4 border-t-4 col-span-2 border-cyan-700">
                {children}
              </section>
              <nav className="flex">
                <div className="mx-auto">
                  <ul className="px-4 pt-4 border-l-4 border-t-4 border-cyan-700">
                    <li>
                      <Link href="/about-me">About me</Link>
                    </li>
                    <li>
                      <Link href="/experience">Experience</Link>
                    </li>
                    <li>
                      <Link href="/side-projects">Projects</Link>
                    </li>
                  </ul>
                </div>
              </nav>
            </section>
          </main>
        </div>
      </body>
    </html>
  )
}
